apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: u22iu7sit-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: u22iu7sit-go 
  name: u22iu7sit-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: u22iu7sit-go 
